name: expenses_tracker
description: 'Expenses tracker'
publish_to: 'none'
version: 1.0.0+1

workspace:
  - packages/app_database
  - packages/app_core
  - packages/resources

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: ">=3.27.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # no bloc? T_T
  modulisto: ^2.4.0
  modulisto_flutter: ^2.2.0

  go_router: ^14.8.0
  intl: ^0.20.2
  meta: ^1.15.0
  path: ^1.8.3
  pure: ^0.3.0
  uuid: ^4.5.1
  path_provider: ^2.1.5
  sliver_tools: ^0.2.12
  navigator_resizable: ^1.0.2
  image_picker: ^1.1.2

  # workspace
  app_database:
  app_core:
  resources:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.9.0


flutter:
  uses-material-design: true
  shaders:
  - packages/resources/shaders/shimmer.frag
  assets:
    - assets/images/
  fonts:
  - family: EuclidFlex
    fonts:
      - asset: packages/resources/fonts/EuclidFlex/EuclidFlexBold.ttf
      - asset: packages/resources/fonts/EuclidFlex/EuclidFlexMedium.ttf
      - asset: packages/resources/fonts/EuclidFlex/EuclidFlexRegular.ttf
      - asset: packages/resources/fonts/EuclidFlex/EuclidFlexSemiBold.ttf
  - family: Comfortaa
    fonts:
      - asset: packages/resources/fonts/Comfortaa/Comfortaa-Bold.ttf
      - asset: packages/resources/fonts/Comfortaa/Comfortaa-Light.ttf
      - asset: packages/resources/fonts/Comfortaa/Comfortaa-Medium.ttf
      - asset: packages/resources/fonts/Comfortaa/Comfortaa-Regular.ttf
      - asset: packages/resources/fonts/Comfortaa/Comfortaa-SemiBold.ttf

flutter_gen:
  # assets:
  #   outputs:
  #     package_parameter_enabled: true # <- Add this line.
  output: packages/resources/lib/_assets/ # Optional (default: lib/gen/)
