name: app_core
version: 1.0.0
resolution: workspace

environment:
  sdk: ^3.6.0


dependencies:
  logging: ^1.2.0

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
